import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GNG Collective - Event Management System for Art Enthusiasts in Surakarta, Indonesia",
  description: "GNG Collective is a platform that connects art enthusiasts in Indonesia with exciting events and workshops. Join us to explore the vibrant art scene and unleash your creativity!",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    title: "GNG Collective - Event Management System for Art Enthusiasts in Surakarta, Indonesia",
    description: "Generated by create next app",
    url: "https://gng-collective.vercel.app",
    siteName: "GNG Collective",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "GNG Collective OG Image",
      },
    ],
    locale: "id_ID",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
